stages:
  - setup
  - dev_build
  - dev_deploy
  - stage_build
  - stage_deploy
  - prod_build
  - prod_deploy
  - notify

variables:
  #  CI_DEBUG_TRACE: "true"
  CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
  CONTAINER_IMAGE_LATEST: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  DOCKER_DRIVER: overlay2


include:
  - local: .aws.gitlab-ci.yml
  - local: .gcp.gitlab-ci.yml